FROM python:3.13-slim
LABEL maintainer="helloworld4846@gmail.com"

# 2. Prevent Python from writing .pyc files and force unbuffered logging (crucial for container logs)
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /backend

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["python", "-m", "main"] 